'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''meetingId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meetingId As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''meetingJoinUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meetingJoinUrl As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''createMeeting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createMeeting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''meetingInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meetingInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''getMeetingInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getMeetingInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''topic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topic As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''start_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents start_time As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''duration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duration As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''agenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agenda As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''updateResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''updateMeeting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateMeeting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''addAttend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAttend As Global.System.Web.UI.WebControls.Button
End Class
